### PR TITLE
Upstream changes

### PR DESCRIPTION
**Pull request by stp-ip**
There were a few changes I didn't yet upstream. I tried to separate the various steps into single commits.

### CODE REVIEW

**Comment by stp-ip** [comment]
@aerohub Can I assume upstreaming changes is not something you are open to? If yes I'll close this PR and keep my fork up to date.

**Comment by ryanbaer** [comment]
@aerohub I hate to promote dissent here since you were the first to officially port this theme, but I use this theme and I'll likely switch to @stp-ip's fork if you're not planning on maintaining this / merging in his changes. He made some really solid improvements, especially by breaking the theme into partials.

**Comment by aerohub** [comment]
@stp-ip Thanks, man. Sorry for my silence

**Comment by stp-ip** [comment]
Great. So upstreaming changes is fine? Then I might try to get some more changes going, next time I have some time. Any way to make merges faster next time?

Thanks for your effort. Appreciated.

**Comment by aerohub** [comment]
I hope I'll make merges faster.

**Pull request merged**
